{% set name = "napari-time-slicer" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-time-slicer-{{ version }}.tar.gz
  sha256: 329f7b04952d56aeb9c446fc1d034850d417367e3eaa0d1dd74fa596b5e73fd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - napari-workflows
    - numpy
    - python >=3.7
    - toolz

test:
  imports:
    - napari_time_slicer
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-time-slicer
  summary: A meta plugin for processing timelapse data in napari timepoint by timepoint
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
