{% set name = "napari-time-slicer" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-time-slicer-{{ version }}.tar.gz
  sha256: ba6127be09a5d41be0e5bd98c7142fdd9bb5700c4395c5df1af09bffb1089aa7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - napari-workflows
    - numpy
    - pyqt
    - python >=3.7
    - toolz

test:
  imports:
    - napari_time_slicer
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-time-slicer
  summary: A meta plugin for processing timelapse data in napari timepoint by timepoint
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - haesleinhuepf
